# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build and Test

on:
  workflow_call:
    outputs:
      coverage-artifact-name:
        description: The artifact name of the uploaded coverage
        value: coverage
      coverage-artifact-id:
        description: The artifact ID of the uploaded coverage
        value: ${{ jobs.merge-coverage.outputs.coverage-artifact-id }}
      coverage-artifact-url:
        description: The URL of the uploaded coverage
        value: ${{ jobs.merge-coverage.outputs.coverage-artifact-url }}

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
          - macos
    runs-on: ${{ matrix.os }}-latest
    permissions:
      id-token: write
      attestations: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: |
          mkdir -p dist
          go test -coverprofile dist/${{ matrix.os }}-coverage.out ./...

      - name: Build
        env:
          CGO_ENABLED: 0
        run: go build -v -o dist/protobuild ./main.go

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}
          path: dist/${{ matrix.os }}-coverage.out
          retention-days: 1

  merge-coverage:
    name: Merge Coverage
    needs: [build]
    runs-on: ubuntu-latest
    outputs:
      coverage-artifact-id: ${{ steps.upload-coverage.outputs.artifact-id }}
      coverage-artifact-url: ${{ steps.upload-coverage.outputs.artifact-url }}
    steps:
      - name: Download Coverage
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          path: dist
          merge-multiple: true

      - name: Install gcovmerge
        run: go install github.com/wadey/gocovmerge@latest

      - name: Merge Coverage
        run: |
          merge=$(go env GOPATH)/bin/gocovmerge
          mkdir dist/merged
          ${merge} dist/*-coverage.out > dist/merged/coverage.out

      - name: Upload Coverage
        id: upload-coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: dist/merged/coverage.out
          retention-days: 7
