# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Continuous Integration

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
  workflow_call:
    outputs:
      coverage-artifact-id:
        description: The artifact ID of the uploaded coverage
        value: ${{ jobs.build.outputs.coverage-artifact-id }}
      coverage-artifact-url:
        description: The URL of the uploaded coverage
        value: ${{ jobs.build.outputs.coverage-artifact-url }}
permissions:
  id-token: write
  attestations: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml

  lint:
    name: Lint
    uses: ./.github/workflows/lint.yaml
