# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy Github Pages
on:
  push:
    branches: [master]
  workflow_dispatch:
permissions:
  id-token: write
  attestations: write

jobs:
  coverage:
    name: Generate Coverage
    uses: ./.github/workflows/build.yaml

  lint:
    name: Lint
    uses: ./.github/workflows/lint.yaml

  license:
    name: License
    uses: ./.github/workflows/license.yaml
    with:
      manifest-type: markdown

  docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    needs: [coverage, lint, license]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Download license
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.license.outputs.artifact-name }}
          path: docs/development

      - name: Download coverage
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.coverage.outputs.coverage-artifact-name }}
          path: htmlcov

      - name: Install dependencies
        run: |
          go install golang.org/x/tools/cmd/godoc@latest
          pip install mkdocs
          pip install mkdocs-mermaid2-plugin
          pip install mkdocs-coverage

      - name: Generate coverage report
        run: |
          go tool cover -html=htmlcov/coverage.out -o htmlcov/index.html
          rm htmlcov/coverage.out

      - name: Generate Documentation
        run: mkdocs build

      - name: Generate godocs
        env:
          GO_DOC_HTML_OUTPUT: "${{ github.workspace }}/dist/godoc"
        run: |
          ./tools/generate-godocs.sh
          mv dist/godoc/* "dist/"
          rm -r "dist/godoc/"

      # Some of the doc generation steps above create the directories with
      # 0750 for permissions -- which is triggering warning annotations in the
      # workflow summaries. Manually converting this to 0755 helps to suppress
      # this.
      - name: Fix permissions
        run: |
          find ./dist -type d -exec chmod 0755 {} \;
          find ./dist -type f -name '.lock' -delete

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    name: Deploy to GH Pages
    runs-on: ubuntu-latest
    needs: docs

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Upload GH Pages
        id: deployment
        uses: actions/deploy-pages@v4
